### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by AndrewChubatiuk** [datafuselabs/databend-sqlalchemy#19]
Hey @everpcpc @hantmac 
I'm waiting for support of sqlalchemy 2.0 to be released. could you please let me know when to expect it?
Thanks

**Comment by everpcpc** [comment]
Hi, you could upgrade to 0.4.4 for sqlalchemy 2.0 support.
https://pypi.org/project/databend-sqlalchemy/

**Comment by hantmac** [comment]
> Hey @everpcpc @hantmac I'm waiting for support of sqlalchemy 2.0 to be released. could you please let me know when to expect it? Thanks

@AndrewChubatiuk Be care of the [version Compatibility](https://github.com/datafuselabs/databend-sqlalchemy?tab=readme-ov-file#compatibility) if you upgrade from < 0.4.0
