### ISSUE TITLE
Add the param `stream_results` 

### ISSUE THREAD

**Issue by hantmac** [datafuselabs/databend-sqlalchemy#23]
if `stream_results` = false, pool the rows data into cursor, else call `next` every time.
Also fix https://github.com/datafuselabs/databend-sqlalchemy/issues/22

**Comment by rad-pat** [comment]
Does the current driver implementation of RowIterator represent a server-side cursor? If so, possible the dialect options `supports_server_side_cursors` and `server_side_cursors` are of use also?

**Comment by hantmac** [comment]
> Does the current driver implementation of RowIterator represent a server-side cursor? If so, possible the dialect options `supports_server_side_cursors` and `server_side_cursors` are of use also?

@rad-pat  Because the `databend-sqlalchemy` use the [databend-rust-driver-binding](https://github.com/datafuselabs/bendsql/tree/main/driver) as python driver. So the `RowIterator`  in https://github.com/datafuselabs/bendsql/blob/main/sql/src/rows.rs#L120  has implementation of RowIterator represent a server-side cursor.

**Comment by rad-pat** [comment]
Actually, it looks like flag `server_side_cursors` is the old way anyway, now deprecated in favour of `stream_results`.

**Comment by hantmac** [comment]
> Actually, it looks like flag `server_side_cursors` is the old way anyway, now deprecated in favour of `stream_results`.

We prefer to have a `stream_results` param, and default value is `true`.

**Comment by TCeason** [comment]
Now we can already support server_side_cursors https://github.com/datafuselabs/databend-sqlalchemy/blob/main/databend_sqlalchemy/databend_dialect.py#L609 use this demo to replace stream_result.

```python
import connector
cursor = connector.connect('databend://root:@localhost:8000?sslmode=disable').cursor()
cursor.execute('SELECT * FROM test')
# print(cursor.fetchone())
# print(cursor.fetchall())
for row in cursor:
    print(row)
```
