### ISSUE TITLE
[feat] Support merge command in databend-sqlalchemy

### ISSUE THREAD

**Issue by hantmac** [datafuselabs/databend-sqlalchemy#31]
We plan to support the `merge into` command in sqlalchemy like:

![img_v3_02a6_1b17608b-4109-432b-bb78-44cf6d2e7fbg](https://github.com/datafuselabs/databend-sqlalchemy/assets/7600925/37dd190e-eb30-4716-84e2-100f2e3a10a6)

**Comment by hantmac** [comment]
https://github.com/snowflakedb/snowflake-sqlalchemy/blob/d2b333417ce1faf682465ba9a53f7490d6bfe5a4/src/snowflake/sqlalchemy/custom_commands.py

**Comment by rad-pat** [comment]
Ha, no way. I didn't see this yesterday, but we needed the statement. It's not quite the same as the snowflake implementation, but was based off it. #32

**Comment by hantmac** [comment]
Fixed by https://github.com/datafuselabs/databend-sqlalchemy/pull/32
