### ISSUE TITLE
cursor iterator is infinite

### ISSUE THREAD

**Issue by AndrewChubatiuk** [datafuselabs/databend-sqlalchemy#38]
in a given below example cursor iterator is infinite, is it expected behaviour?
```
from sqlalchemy import create_engine, text
engine = create_engine(
    f"databend://{username}:{password}@{host_port_name}/{database_name}?sslmode=disable"
)
connection = engine.connect()
cursor = connection.execute(text("SELECT 1")).cursor
for row in cursor:
    print(row)
```

**Comment by hantmac** [comment]
@AndrewChubatiuk Hi you should use:

```
for row in cursor.next():
    print(row)
```

**Comment by AndrewChubatiuk** [comment]
i'm not sure it works
`row` value in a loop returns value in each column of a single row, retrieved during cursor.next() call. next method uses `return` instead of yield
i made it working in an ugly way
```
for row in cursor:
   if row is None:
       break
   print(row)
```

**Comment by AndrewChubatiuk** [comment]
https://github.com/datafuselabs/databend-sqlalchemy/pull/39
